### ISSUE TITLE
v0.11.0 uses LZ4 v1.8.1.2

### ISSUE THREAD

**Issue by hhromic** [Iotic-Labs/py-lz4framed#15]
Hi guys,
first thanks for your python library! it proved to be very useful for my research work which needs to store a lot of gigabytes of data.

Secondly, the current version of lz4 is now v1.8.1.2, with v1.8.1 being deprecated:
https://github.com/lz4/lz4/releases/tag/v1.8.1

The code is exactly the same it seems, but with a packaging mistake. Are you planning on getting up-to-date with it or just wait for the next major version?
I think keeping the versions up-to-date is less confusing :).

Thanks again!

**Comment by vtermanis** [comment]
Yes, I agree it is a bit confusing.

From what I understand the only change is [this commit](https://github.com/lz4/lz4/commit/47bf1a9f010d548fa58c7716678e7a11b356b120). However, py-lz4framed v0.11.0 should already have that version ([see here](https://github.com/Iotic-Labs/py-lz4framed/blob/v0.11.0/lz4/lz4.h#L96)). As you can see from the source code, there is no 4th version specifier (only major, minor & release) so there wouldn't be anywhere that 1.8.1 **.2** could be shown.
As such there isn't anything new to release, unless I'm mistaken (other than a note in e.g. the `CHANGELOG` but that wouldn't warrant a version bump).

If `python3 -c "import lz4framed; print(lz4framed.LZ4_VERSION)"` shows `1.8.1` (which is taken from the above linked `lz4.h` define) then it's up-to-date (and equivalent to 1.8.1.2)

Hope that helps.

**Comment by hhromic** [comment]
Thanks for your answer.
I just did a release-tag comparison between `v1.8.1` and `v1.8.1.2` here: https://github.com/lz4/lz4/compare/v1.8.1...v1.8.1.2

Looks like there are multiple commits between those two releases, including the commit you mention, beyond just the version number change in code. Maybe I'm missing something?

Anyway to avoid further confusion, maybe is best to wait for the next release and all should be in-sync again?

**Comment by vtermanis** [comment]
You're right, there's something strange going on with the label. However, if I download the [tgz archive for v.1.8.1.2](https://github.com/lz4/lz4/archive/v1.8.1.2.tar.gz) and compare the lib source files with what is in py-lzframed v0.11.0, they come out as identical. (Maybe v1.8.1 was actually a pre-release version or something.)

I'll keep an eye out for new releases.

**Comment by hhromic** [comment]
Interesting.
I just checked and the lz4 source code you have in py-lzframed is not the same as the [tgz archive for v1.8.1](https://github.com/lz4/lz4/archive/v1.8.1.tar.gz) that you download either.
Maybe when you grabbed the code the archive was different at the time?
Basically this would mean you already grabbed the v1.8.1.2 code in disguise of v1.8.1.

So, seems that the best thing to do is to wait for the next release, wait a day or so and then update py-lzframed accordingly to sync-up the versions. Maybe you can keep this issue open as a reminder?

**Comment by vtermanis** [comment]
> Maybe when you grabbed the code the archive was different at the time?

Since 1.8.1.2 supersedes 1.8.1 and is just a minor patch, I did indeed download 1.8.1.2. With hindsight I could have explicitly mentioned in the README that it is 1.8.1.2 and not 1.8.1 (and that would be the only place where said difference would be visible). But the fact remains that it's fully up-to-date. (I always wait a significant amount of time before including a new lz4 release exactly to avoid having to re-release a slightly altered patch version.)

> accordingly to sync-up the versions

I don't agree that versions are out-of-sync. There is nowhere in the lz4frame library where it would be possible to read out the 1.8.1.2 version change since the `LZ4_VERSION_NUMBER` only exposes three numbers, not four.

But it is good to summarise for anyone else: **py-lz4framed v.0.11.0** uses **lz4 v1.8.1.2**

I have also [updated the release](https://github.com/Iotic-Labs/py-lz4framed/releases/tag/v0.11.0) with a comment to reflect that as well as change this issue's title.

**Comment by hhromic** [comment]
> I don't agree that versions are out-of-sync. 

Sorry I meantthat the *labelled* version in py-lz4framed is v1.8.1 but the actual code is v1.8.1.2, hence the "out of sync". But after your comment, it is 100% clear to me now that in fact it is using v1.8.1.2.

I think that now that things are clear and even clarified in the releases page, it is safe to close this issue.
Thanks a lot for your time!

**Comment by vtermanis** [comment]
> Thanks a lot for your time!

You're welcome. If a new lz4 version is released and I haven't noticed (due to work commitments), please feel free to raise a new issue.
